'use strict';

let Configuration = {

	lexicon:
    {
      en: [
		  	{ word: "arête" },
      	{ word: "epilobium" },
      	{ word: "metaphysical" },
      	{ word: "occasioning" },
      	{ word: "rassling"
      	},
      	{
      	    word: "subchondral"
      	},
      	{
      	    word: "unfoldable"
      	},
      	{
      	    word: "unreason"
      	},
      	{
      	    word: "unsupplemented"
      	},
      	{
      	    word: "vennel"
      	},
      	{
      	    word: "Butte"
      	},
      	{
      	    word: "Caesareans"
      	},
      	{
      	    word: "Keepers"
      	},
      	{
      	    word: "cinerary"
      	},
      	{
      	    word: "commentaries"
      	},
      	{
      	    word: "fusible"
      	},
      	{
      	    word: "lysophosphatidic"
      	},
      	{
      	    word: "metacommunity"
      	},
      	{
      	    word: "rag-tag"
      	},
      	{
      	    word: "tremors"
      	},
      	{
      	    word: "Moreton Bay"
      	},
      	{
      	    word: "Mortimer"
      	},
      	{
      	    word: "areolar"
      	},
      	{
      	    word: "dabbawalas"
      	},
      	{
      	    word: "diplomatically"
      	},
      	{
      	    word: "leakiness"
      	},
      	{
      	    word: "river-dolphin"
      	},
      	{
      	    word: "supercities"
      	},
      	{
      	    word: "tester"
      	},
      	{
      	    word: "tigerlike"
      	},
      	{
      	    word: "Carrick"
      	},
      	{
      	    word: "audiocassette"
      	},
      	{
      	    word: "circumnavigator"
      	},
      	{
      	    word: "dispart"
      	},
      	{
      	    word: "multiposition"
      	},
      	{
      	    word: "obliged"
      	},
      	{
      	    word: "perishables"
      	},
      	{
      	    word: "supercells"
      	},
      	{
      	    word: "transpositive"
      	},
      	{
      	    word: "universalisability"
      	},
      	{
      	    word: "Youngstown"
      	},
      	{
      	    word: "appropriability"
      	},
      	{
      	    word: "centaury"
      	},
      	{
      	    word: "chicer"
      	},
      	{
      	    word: "chronobiology"
      	},
      	{
      	    word: "latecomers"
      	},
      	{
      	    word: "soften"
      	},
      	{
      	    word: "steamie"
      	},
      	{
      	    word: "westie"
      	},
      	{
      	    word: "widening"
      	},
      	{
      	    word: "Navajo"
      	},
      	{
      	    word: "adnexed"
      	},
      	{
      	    word: "burthenous"
      	},
      	{
      	    word: "defibrillator"
      	},
      	{
      	    word: "enchainment"
      	},
      	{
      	    word: "followers"
      	},
      	{
      	    word: "incentives"
      	},
      	{
      	    word: "precocity"
      	},
      	{
      	    word: "two-phase"
      	},
      	{
      	    word: "unparliamentary"
      	}
    	],
    	fr: [
      	{ word: 'bleu' },
      	{ word: 'super' },
      	{ word: 'autre' },
      	{ word: 'bizarre' },
      	{ word: 'difficile' },
      	{ word: 'drôle' },
      	{ word: 'étrange' },
      	{ word: 'facile' },
      	{ word: 'grave' },
      	{ word: 'impossible' },
      	{ word: 'jeune' },
      	{ word: 'juste' },
      	{ word: 'libre' },
      	{ word: 'malade' },
      	{ word: 'même' },
      	{ word: 'pauvre' },
      	{ word: 'possible' },
      	{ word: 'propre' },
      	{ word: 'rouge' },
      	{ word: 'sale' },
      	{ word: 'simple' },
      	{ word: 'tranquille' },
      	{ word: 'triste' },
      	{ word: 'vide' },
      	{ word: 'bonne' },
      	{ word: 'toute' },
      	{ word: 'doux' },
      	{ word: 'faux' },
      	{ word: 'français' },
      	{ word: 'gros' },
      	{ word: 'heureux' },
      	{ word: 'mauvais' },
      	{ word: 'sérieux' },
      	{ word: 'vieux' },
      	{ word: 'vrai' },
      	{ word: 'ancien' },
      	{ word: 'beau' },
      	{ word: 'blanc' },
      	{ word: 'certain' },
      	{ word: 'chaud' },
      	{ word: 'cher' },
      	{ word: 'clair' },
      	{ word: 'content' },
      	{ word: 'dernier' },
      	{ word: 'désolé' },
      	{ word: 'différent' },
      	{ word: 'droit' },
      	{ word: 'entier' },
      	{ word: 'fort' },
      	{ word: 'froid' },
      	{ word: 'gentil' },
      	{ word: 'grand' },
      	{ word: 'haut' },
      	{ word: 'humain' },
      	{ word: 'important' },
      	{ word: 'joli' },
      	{ word: 'léger' },
      	{ word: 'long' },
      	{ word: 'meilleur' },
      	{ word: 'mort' },
      	{ word: 'noir' },
      	{ word: 'nouveau' },
      	{ word: 'pareil' },
      	{ word: 'petit' },
      	{ word: 'plein' },
      	{ word: 'premier' },
      	{ word: 'prêt' },
      	{ word: 'prochain' },
      	{ word: 'quoi' },
      	{ word: 'seul' },
      	{ word: 'tout' },
      	{ word: 'vert' },
      	{ word: 'vivant' },
      	{ word: 'aide' },
      	{ word: 'chef' },
      	{ word: 'enfant' },
      	{ word: 'garde' },
      	{ word: 'gauche' },
      	{ word: 'geste' },
      	{ word: 'gosse' },
      	{ word: 'livre' },
      	{ word: 'merci' },
      	{ word: 'mort' },
      	{ word: 'ombre' },
      	{ word: 'part' },
      	{ word: 'poche' },
      	{ word: 'professeur' },
      	{ word: 'tour' },
      	{ word: 'fois' },
      	{ word: 'madame' },
      	{ word: 'paix' },
      	{ word: 'voix' },
      	{ word: 'affaire' },
      	{ word: 'année' },
      	{ word: 'arme' },
      	{ word: 'armée' },
      	{ word: 'attention' },
      	{ word: 'balle' },
      	{ word: 'boîte' },
      	{ word: 'bouche' },
      	{ word: 'carte' },
      	{ word: 'cause' },
      	{ word: 'chambre' },
      	{ word: 'chance' },
      	{ word: 'chose' },
      	{ word: 'classe' },
      	{ word: 'confiance' },
      	{ word: 'couleur' },
      	{ word: 'cour' },
      	{ word: 'cuisine' },
      	{ word: 'dame' },
      	{ word: 'dent' },
      	{ word: 'droite' },
      	{ word: 'école' },
      	{ word: 'église' },
      	{ word: 'envie' },
      	{ word: 'épaule' },
      	{ word: 'époque' },
      	{ word: 'équipe' },
      	{ word: 'erreur' },
      	{ word: 'espèce' },
      	{ word: 'face' },
      	{ word: 'façon' },
      	{ word: 'faim' },
      	{ word: 'famille' },
      	{ word: 'faute' },
      	{ word: 'femme' },
      	{ word: 'fenêtre' },
      	{ word: 'fête' },
      	{ word: 'fille' },
      	{ word: 'fleur' },
      	{ word: 'force' },
      	{ word: 'forme' },
      	{ word: 'guerre' },
      	{ word: 'gueule' },
      	{ word: 'habitude' },
      	{ word: 'heure' },
      	{ word: 'histoire' },
      	{ word: 'idée' },
      	{ word: 'image' },
      	{ word: 'impression' },
      	{ word: 'jambe' },
      	{ word: 'joie' },
      	{ word: 'journée' },
      	{ word: 'langue' },
      	{ word: 'lettre' },
      	{ word: 'lèvre' },
      	{ word: 'ligne' },
      	{ word: 'lumière' },
      	{ word: 'main' },
      	{ word: 'maison' },
      	{ word: 'maman' },
      	{ word: 'manière' },
      	{ word: 'marche' },
      	{ word: 'merde' },
      	{ word: 'mère' },
      	{ word: 'minute' },
      	{ word: 'musique' },
      	{ word: 'nuit' },
      	{ word: 'odeur' },
      	{ word: 'oreille' },
      	{ word: 'parole' },
      	{ word: 'partie' },
      	{ word: 'peau' },
      	{ word: 'peine' },
      	{ word: 'pensée' },
      	{ word: 'personne' },
      	{ word: 'peur' },
      	{ word: 'photo' },
      	{ word: 'pièce' },
      	{ word: 'pierre' },
      	{ word: 'place' },
      	{ word: 'police' },
      	{ word: 'porte' },
      	{ word: 'présence' },
      	{ word: 'prison' },
      	{ word: 'putain' },
      	{ word: 'question' },
      	{ word: 'raison' },
      	{ word: 'réponse' },
      	{ word: 'robe' },
      	{ word: 'route' },
      	{ word: 'salle' },
      	{ word: 'scène' },
      	{ word: 'seconde' },
      	{ word: 'sécurité' },
      	{ word: 'semaine' },
      	{ word: 'situation' },
      	{ word: 'soeur' },
      	{ word: 'soirée' },
      	{ word: 'sorte' },
      	{ word: 'suite' },
      	{ word: 'table' },
      	{ word: 'terre' },
      	{ word: 'tête' },
      	{ word: 'vérité' },
      	{ word: 'ville' },
      	{ word: 'voiture' },
      	{ word: 'avis' },
      	{ word: 'bois' },
      	{ word: 'bras' },
      	{ word: 'choix' },
      	{ word: 'corps' },
      	{ word: 'cours' },
      	{ word: 'gars' },
      	{ word: 'mois' },
      	{ word: 'pays' },
      	{ word: 'prix' },
      	{ word: 'propos' },
      	{ word: 'sens' },
      	{ word: 'temps' },
      	{ word: 'travers' },
      	{ word: 'vieux' },
      	{ word: 'accord' },
      	{ word: 'agent' },
      	{ word: 'amour' },
      	{ word: 'appel' },
      	{ word: 'arbre' },
      	{ word: 'argent' },
      	{ word: 'avenir' },
      	{ word: 'avion' },
      	{ word: 'bateau' },
      	{ word: 'bébé' },
      	{ word: 'besoin' },
      	{ word: 'bonheur' },
      	{ word: 'bonjour' },
      	{ word: 'bord' },
      	{ word: 'boulot' },
      	{ word: 'bout' },
      	{ word: 'bruit' },
      	{ word: 'bureau' },
      	{ word: 'café' },
      	{ word: 'camp' },
      	{ word: 'capitaine' },
      	{ word: 'chat' },
      	{ word: 'chemin' },
      	{ word: 'chéri' },
      	{ word: 'cheval' },
      	{ word: 'cheveu' },
      	{ word: 'chien' },
      	{ word: 'ciel' },
      	{ word: 'client' },
      	{ word: 'c&oelig;ur' },
      	{ word: 'coin' },
      	{ word: 'colonel' },
      	{ word: 'compte' },
      	{ word: 'copain' },
      	{ word: 'côté' },
      	{ word: 'coup' },
      	{ word: 'courant' },
      	{ word: 'début' },
      	{ word: 'départ' },
      	{ word: 'dieu' },
      	{ word: 'docteur' },
      	{ word: 'doigt' },
      	{ word: 'dollar' },
      	{ word: 'doute' },
      	{ word: 'droit' },
      	{ word: 'effet' },
      	{ word: 'endroit' },
      	{ word: 'ennemi' },
      	{ word: 'escalier' },
      	{ word: 'esprit' },
      	{ word: 'état' },
      	{ word: 'être' },
      	{ word: 'exemple' },
      	{ word: 'fait' },
      	{ word: 'film' },
      	{ word: 'flic' },
      	{ word: 'fond' },
      	{ word: 'français' },
      	{ word: 'frère' },
      	{ word: 'front' },
      	{ word: 'garçon' },
      	{ word: 'général' },
      	{ word: 'genre' },
      	{ word: 'goût' },
      	{ word: 'gouvernement' },
      	{ word: 'grand' },
      	{ word: 'groupe' },
      	{ word: 'haut' },
      	{ word: 'homme' },
      	{ word: 'honneur' },
      	{ word: 'hôtel' },
      	{ word: 'instant' },
      	{ word: 'intérêt' },
      	{ word: 'intérieur' },
      	{ word: 'jardin' },
      	{ word: 'jour' },
      	{ word: 'journal' },
      	{ word: 'lieu' },
      	{ word: 'long' },
      	{ word: 'maître' },
      	{ word: 'mari' },
      	{ word: 'mariage' },
      	{ word: 'matin' },
      	{ word: 'médecin' },
      	{ word: 'mètre' },
      	{ word: 'milieu' },
      	{ word: 'million' },
      	{ word: 'moment' },
      	{ word: 'monde' },
      	{ word: 'monsieur' },
      	{ word: 'mouvement' },
      	{ word: 'moyen' },
      	{ word: 'noir' },
      	{ word: 'nouveau' },
      	{ word: 'numéro' },
      	{ word: 'oeil' },
      	{ word: 'oiseau' },
      	{ word: 'oncle' },
      	{ word: 'ordre' },
      	{ word: 'papa' },
      	{ word: 'papier' },
      	{ word: 'parent' },
      	{ word: 'passage' },
      	{ word: 'passé' },
      	{ word: 'patron' },
      	{ word: 'père' },
      	{ word: 'petit' },
      	{ word: 'peuple' },
      	{ word: 'pied' },
      	{ word: 'plaisir' },
      	{ word: 'plan' },
      	{ word: 'point' },
      	{ word: 'pouvoir' },
      	{ word: 'premier' },
      	{ word: 'présent' },
      	{ word: 'président' },
      	{ word: 'prince' },
      	{ word: 'problème' },
      	{ word: 'quartier' },
      	{ word: 'rapport' },
      	{ word: 'regard' },
      	{ word: 'reste' },
      	{ word: 'retard' },
      	{ word: 'retour' },
      	{ word: 'rêve' },
      	{ word: 'revoir' },
      	{ word: 'salut' },
      	{ word: 'sang' },
      	{ word: 'secret' },
      	{ word: 'seigneur' },
      	{ word: 'sentiment' },
      	{ word: 'service' },
      	{ word: 'seul' },
      	{ word: 'siècle' },
      	{ word: 'signe' },
      	{ word: 'silence' },
      	{ word: 'soir' },
      	{ word: 'soldat' },
      	{ word: 'soleil' },
      	{ word: 'sourire' },
      	{ word: 'souvenir' },
      	{ word: 'sujet' },
      	{ word: 'téléphone' },
      	{ word: 'tout' },
      	{ word: 'train' },
      	{ word: 'travail' },
      	{ word: 'trou' },
      	{ word: 'truc' },
      	{ word: 'type' },
      	{ word: 'vent' },
      	{ word: 'ventre' },
      	{ word: 'verre' },
      	{ word: 'village' },
      	{ word: 'visage' },
      	{ word: 'voyage' },
      	{ word: 'fils' },
      	{ word: 'gens' },
      	{ word: 'abandonner' },
      	{ word: 'accepter' },
      	{ word: 'accompagner' },
      	{ word: 'acheter' },
      	{ word: 'adorer' },
      	{ word: 'agir' },
      	{ word: 'aider' },
      	{ word: 'aimer' },
      	{ word: 'ajouter' },
      	{ word: 'aller' },
      	{ word: 'amener' },
      	{ word: 'amuser' },
      	{ word: 'annoncer' },
      	{ word: 'apercevoir' },
      	{ word: 'apparaître' },
      	{ word: 'appeler' },
      	{ word: 'apporter' },
      	{ word: 'apprendre' },
      	{ word: 'approcher' },
      	{ word: 'arranger' },
      	{ word: 'arrêter' },
      	{ word: 'arriver' },
      	{ word: 'asseoir' },
      	{ word: 'assurer' },
      	{ word: 'attaquer' },
      	{ word: 'atteindre' },
      	{ word: 'attendre' },
      	{ word: 'avancer' },
      	{ word: 'avoir' },
      	{ word: 'baisser' },
      	{ word: 'battre' },
      	{ word: 'boire' },
      	{ word: 'bouger' },
      	{ word: 'brûler' },
      	{ word: 'cacher' },
      	{ word: 'calmer' },
      	{ word: 'casser' },
      	{ word: 'cesser' },
      	{ word: 'changer' },
      	{ word: 'chanter' },
      	{ word: 'charger' },
      	{ word: 'chercher' },
      	{ word: 'choisir' },
      	{ word: 'commencer' },
      	{ word: 'comprendre' },
      	{ word: 'compter' },
      	{ word: 'conduire' },
      	{ word: 'connaître' },
      	{ word: 'continuer' },
      	{ word: 'coucher' },
      	{ word: 'couper' },
      	{ word: 'courir' },
      	{ word: 'couvrir' },
      	{ word: 'craindre' },
      	{ word: 'crier' },
      	{ word: 'croire' },
      	{ word: 'danser' },
      	{ word: 'décider' },
      	{ word: 'découvrir' },
      	{ word: 'dégager' },
      	{ word: 'demander' },
      	{ word: 'descendre' },
      	{ word: 'désoler' },
      	{ word: 'détester' },
      	{ word: 'détruire' },
      	{ word: 'devenir' },
      	{ word: 'deviner' },
      	{ word: 'devoir' },
      	{ word: 'dire' },
      	{ word: 'disparaître' },
      	{ word: 'donner' },
      	{ word: 'dormir' },
      	{ word: 'échapper' },
      	{ word: 'écouter' },
      	{ word: 'écrire' },
      	{ word: 'éloigner' },
      	{ word: 'embrasser' },
      	{ word: 'emmener' },
      	{ word: 'empêcher' },
      	{ word: 'emporter' },
      	{ word: 'enlever' },
      	{ word: 'entendre' },
      	{ word: 'entrer' },
      	{ word: 'envoyer' },
      	{ word: 'espérer' },
      	{ word: 'essayer' },
      	{ word: 'être' },
      	{ word: 'éviter' },
      	{ word: 'excuser' },
      	{ word: 'exister' },
      	{ word: 'expliquer' },
      	{ word: 'faire' },
      	{ word: 'falloir' },
      	{ word: 'fermer' },
      	{ word: 'filer' },
      	{ word: 'finir' },
      	{ word: 'foutre' },
      	{ word: 'frapper' },
      	{ word: 'gagner' },
      	{ word: 'garder' },
      	{ word: 'glisser' },
      	{ word: 'habiter' },
      	{ word: 'ignorer' },
      	{ word: 'imaginer' },
      	{ word: 'importer' },
      	{ word: 'inquiéter' },
      	{ word: 'installer' },
      	{ word: 'intéresser' },
      	{ word: 'inviter' },
      	{ word: 'jeter' },
      	{ word: 'jouer' },
      	{ word: 'jurer' },
      	{ word: 'lâcher' },
      	{ word: 'laisser' },
      	{ word: 'lancer' },
      	{ word: 'lever' },
      	{ word: 'lire' },
      	{ word: 'maintenir' },
      	{ word: 'manger' },
      	{ word: 'manquer' },
      	{ word: 'marcher' },
      	{ word: 'marier' },
      	{ word: 'mener' },
      	{ word: 'mentir' },
      	{ word: 'mettre' },
      	{ word: 'monter' },
      	{ word: 'montrer' },
      	{ word: 'mourir' },
      	{ word: 'naître' },
      	{ word: 'obliger' },
      	{ word: 'occuper' },
      	{ word: 'offrir' },
      	{ word: 'oser' },
      	{ word: 'oublier' },
      	{ word: 'ouvrir' },
      	{ word: 'paraître' },
      	{ word: 'parler' },
      	{ word: 'partir' },
      	{ word: 'passer' },
      	{ word: 'payer' },
      	{ word: 'penser' },
      	{ word: 'perdre' },
      	{ word: 'permettre' },
      	{ word: 'plaire' },
      	{ word: 'pleurer' },
      	{ word: 'porter' },
      	{ word: 'poser' },
      	{ word: 'pousser' },
      	{ word: 'pouvoir' },
      	{ word: 'préférer' },
      	{ word: 'prendre' },
      	{ word: 'préparer' },
      	{ word: 'présenter' },
      	{ word: 'prévenir' },
      	{ word: 'prier' },
      	{ word: 'promettre' },
      	{ word: 'proposer' },
      	{ word: 'protéger' },
      	{ word: 'quitter' },
      	{ word: 'raconter' },
      	{ word: 'ramener' },
      	{ word: 'rappeler' },
      	{ word: 'recevoir' },
      	{ word: 'reconnaître' },
      	{ word: 'réfléchir' },
      	{ word: 'refuser' },
      	{ word: 'regarder' },
      	{ word: 'rejoindre' },
      	{ word: 'remarquer' },
      	{ word: 'remettre' },
      	{ word: 'remonter' },
      	{ word: 'rencontrer' },
      	{ word: 'rendre' },
      	{ word: 'rentrer' },
      	{ word: 'répéter' },
      	{ word: 'répondre' },
      	{ word: 'reposer' },
      	{ word: 'reprendre' },
      	{ word: 'ressembler' },
      	{ word: 'rester' },
      	{ word: 'retenir' },
      	{ word: 'retirer' },
      	{ word: 'retourner' },
      	{ word: 'retrouver' },
      	{ word: 'réussir' },
      	{ word: 'réveiller' },
      	{ word: 'revenir' },
      	{ word: 'rêver' },
      	{ word: 'revoir' },
      	{ word: 'rire' },
      	{ word: 'risquer' },
      	{ word: 'rouler' },
      	{ word: 'sauter' },
      	{ word: 'sauver' },
      	{ word: 'savoir' },
      	{ word: 'sembler' },
      	{ word: 'sentir' },
      	{ word: 'séparer' },
      	{ word: 'serrer' },
      	{ word: 'servir' },
      	{ word: 'sortir' },
      	{ word: 'souffrir' },
      	{ word: 'sourire' },
      	{ word: 'souvenir' },
      	{ word: 'suffire' },
      	{ word: 'suivre' },
      	{ word: 'taire' },
      	{ word: 'tendre' },
      	{ word: 'tenir' },
      	{ word: 'tenter' },
      	{ word: 'terminer' },
      	{ word: 'tirer' },
      	{ word: 'tomber' },
      	{ word: 'toucher' },
      	{ word: 'tourner' },
      	{ word: 'traîner' },
      	{ word: 'traiter' },
      	{ word: 'travailler' },
      	{ word: 'traverser' },
      	{ word: 'tromper' },
      	{ word: 'trouver' },
      	{ word: 'tuer' },
      	{ word: 'utiliser' },
      	{ word: 'valoir' },
      	{ word: 'vendre' },
      	{ word: 'venir' },
      	{ word: 'vivre' },
      	{ word: 'voir' },
      	{ word: 'voler' },
      	{ word: 'vouloir' }
    	]
    }
}

module.exports = Configuration;